export const dashboardStats = [
  {
    title: "Total Enquiries",
    description: "Total number of enquiries",
    value: 37,
  },
  {
    title: "Total Visitors",
    description: "Total number of visitors",
    value: 1842,
  },
  {
    title: "Total Properties",
    description: "Total number of properties",
    value: 12,
  },
  {
    title: "Active Listings",
    description: "Total number of active listings",
    value: 8,
  },
  // {
  //   title: "Inactive Listings",
  //   description: "Total number of inactive listings",
  //   value: 3,
  // },
  // {
  //   title: "Draft Listings",
  //   description: "Total number of draft listings",
  //   value: 1,
  // },
  
  
];
export const viewsChartData = {
  last7Days: [
    { day: "Mon", views: 120 },
    { day: "Tue", views: 145 },
    { day: "Wed", views: 98 },
    { day: "Thu", views: 165 },
    { day: "Fri", views: 210 },
    { day: "Sat", views: 260 },
    { day: "Sun", views: 180 },
  ],

  last30Days: [
    { day: "Week 1", views: 820 },
    { day: "Week 2", views: 960 },
    { day: "Week 3", views: 1120 },
    { day: "Week 4", views: 1340 },
  ],
}
export const inquiries = [
  {
    id: "inq-1",
    userName: "Amit Sharma",
    propertyName: "2BHK Apartment - Andheri",
    status: "New",
    contactNumber: "+91 98765 43210",
  },
  {
    id: "inq-2",
    userName: "Priya Verma",
    propertyName: "Studio Flat - Koramangala",
    status: "Contacted",
    contactNumber: "+91 91234 56789",
  },
  {
    id: "inq-3",
    userName: "Rahul Mehta",
    propertyName: "3BHK Villa - Whitefield",
    status: "Pending",
    contactNumber: "+91 99887 66554",
  },
  {
    id: "inq-4",
    userName: "Sneha Kapoor",
    propertyName: "1BHK Apartment - Powai",
    status: "Closed",
    contactNumber: "+91 90909 80808",
  },
  {
    id: "inq-5",
    userName: "Arjun Nair",
    propertyName: "2BHK Flat - HSR Layout",
    status: "New",
    contactNumber: "+91 95555 44433",
  },
]

export const properties = [
  {
    id: "prop-1",
    name: "2BHK Apartment - Andheri East",
    location: "Mumbai",
    rent: 35000,
    status: "active",
    views: 320,
    enquiries: 12,
    createdAt: "2025-12-01",
    lastUpdated: "2 days ago",
  },
  {
    id: "prop-2",
    name: "1BHK Apartment - Powai",
    location: "Mumbai",
    rent: 28000,
    status: "active",
    views: 210,
    enquiries: 8,
    createdAt: "2025-11-20",
    lastUpdated: "5 days ago",
  },
  {
    id: "prop-3",
    name: "Studio Flat - Koramangala",
    location: "Bangalore",
    rent: 22000,
    status: "active",
    views: 410,
    enquiries: 15,
    createdAt: "2025-10-15",
    lastUpdated: "1 day ago",
  },
  {
    id: "prop-4",
    name: "3BHK Villa - Whitefield",
    location: "Bangalore",
    rent: 55000,
    status: "inactive",
    views: 95,
    enquiries: 3,
    createdAt: "2025-09-05",
    lastUpdated: "10 days ago",
  },
  {
    id: "prop-5",
    name: "2BHK Flat - HSR Layout",
    location: "Bangalore",
    rent: 32000,
    status: "active",
    views: 275,
    enquiries: 9,
    createdAt: "2025-11-01",
    lastUpdated: "3 days ago",
  },
  {
    id: "prop-6",
    name: "1BHK Apartment - Baner",
    location: "Pune",
    rent: 20000,
    status: "draft",
    views: 0,
    enquiries: 0,
    createdAt: "2025-12-20",
    lastUpdated: "Today",
  },
  {
    id: "prop-7",
    name: "2BHK Apartment - Wakad",
    location: "Pune",
    rent: 26000,
    status: "active",
    views: 180,
    enquiries: 6,
    createdAt: "2025-10-10",
    lastUpdated: "6 days ago",
  },
  {
    id: "prop-8",
    name: "3BHK Apartment - Gachibowli",
    location: "Hyderabad",
    rent: 42000,
    status: "active",
    views: 360,
    enquiries: 11,
    createdAt: "2025-09-18",
    lastUpdated: "4 days ago",
  },
  {
    id: "prop-9",
    name: "2BHK Flat - Indiranagar",
    location: "Bangalore",
    rent: 38000,
    status: "inactive",
    views: 140,
    enquiries: 4,
    createdAt: "2025-08-25",
    lastUpdated: "15 days ago",
  },
  {
    id: "prop-10",
    name: "1RK Studio - Viman Nagar",
    location: "Pune",
    rent: 18000,
    status: "active",
    views: 195,
    enquiries: 7,
    createdAt: "2025-11-12",
    lastUpdated: "2 days ago",
  },
]
